version: '3.8'

services:
  plex-to-arrs:
    build: .
    container_name: plex-to-arrs
    restart: unless-stopped
    environment:
      # Plex Configuration
      PLEX_TOKEN: ${PLEX_TOKEN}
      FETCH_ALL_USER_WATCHLISTS: ${FETCH_ALL_USER_WATCHLISTS:-false}
      
      # Radarr Configuration
      RADARR_URL: ${RADARR_URL}
      RADARR_API_KEY: ${RADARR_API_KEY}
      RADARR_QUALITY_PROFILE: ${RADARR_QUALITY_PROFILE:-10}
      
      # Sonarr Configuration  
      SONARR_URL: ${SONARR_URL}
      SONARR_API_KEY: ${SONARR_API_KEY}
      SONARR_QUALITY_PROFILE: ${SONARR_QUALITY_PROFILE:-8}
      
      # TMDB Configuration
      TMDB_API_KEY: ${TMDB_API_KEY}
      
      # Optional: Run sync immediately on startup
      RUN_ON_STARTUP: ${RUN_ON_STARTUP:-false}
      
      # Cache refresh interval (hours)
      CACHE_REFRESH_HOURS: ${CACHE_REFRESH_HOURS:-24}
      
      # Timezone for proper scheduling
      TZ: ${TZ:-Europe/Amsterdam}
    
    volumes:
      # Mount logs directory to persist logs and cache
      - ./logs:/app/logs
      
    # Optional: expose port for health checks
    # ports:
    #   - "8080:8080"
    
    labels:
      - "com.docker.compose.project=plex-to-arrs"
      - "description=Daily Plex Watchlist to Radarr/Sonarr Sync"